In [46]:
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 21 14:45:49 2018
Mean-Squared-Displacement Analyzer for multiple tracks
@author: deepak90
"""
import numpy as np
# import Track
import os
import imp
import matplotlib.pyplot as plt
import scipy.interpolate as interpolate
from cycler import cycler
import pandas as pd

def vector_dot(vec_a, vec_b):
    # General dot product between arrays of vectors
    try:
        nDimsA, LenA = np.shape(vec_a)
    except:
        nDimsA = len(vec_a)
        LenA = 1
    try:
        nDimsB, LenB = np.shape(vec_b)
    except: 
        nDimsB = len(vec_b)
        LenB = 1
    
    assert(nDimsA == nDimsB)
    assert(LenA==LenB or LenA==1 or LenB==1)
    
    result = np.zeros((1, max(LenA, LenB)))
    
    result = vec_a[0,:]*vec_b[0,:] + vec_a[1,:]*vec_b[1,:] + vec_a[2,:]*vec_b[2,:]
    
    
    return result
        
        
    

vector = np.random.normal(0,1, (3,100))

vector_mag = (vector[0,:]**2 + vector[1,:]**2 + vector[2,:]**2 )**(1/2)

vector_unit = np.zeros_like(vector)

vector_unit[0,:] = vector[0,:]/vector_mag
vector_unit[1,:] = vector[1,:]/vector_mag
vector_unit[2,:] = vector[2,:]/vector_mag

g_vector = [0,0,1]
g_vector= np.transpose(g_vector)

print(np.shape(g_vector))


dotproduct = vector_dot(vector, g_vector)

print(dotproduct**(1/2))



(3,)


IndexError: too many indices for array

In [31]:
a = np.random.rand(3,)
b = np.random.rand(3,)
print(a)

[0.47648655 0.55645164 0.01716867]


In [17]:
print(np.shape(a))

(3, 10)


In [32]:
C = np.dot(a, b)
print(C)
print(np.shape(C))

0.3181706842324888
()


In [21]:
D = np.inner(a,b)

In [22]:
print(D)

[[3.25520186 3.04354253 1.87873528]
 [2.70585691 2.61184038 1.69592979]
 [2.92160474 3.15511245 1.98104978]]


[[0.09087913 0.21962502 0.16842207 0.20575282 0.16699098 0.18880674
  0.22847932 0.19380819 0.13698594 0.23385144]
 [0.3801893  1.27763944 0.61732982 1.04392723 0.51975806 0.83976999
  1.22655607 1.17069293 0.84460172 1.00936379]
 [0.82926602 1.72496655 0.90442468 1.32762478 1.28540943 1.31216607
  1.58796683 1.71502265 1.41797243 1.60833146]
 [0.21276449 0.30391645 0.06132252 0.15091672 0.28870227 0.20881479
  0.21922461 0.36706845 0.36958643 0.25427139]
 [0.3346835  0.41834974 0.21894448 0.269721   0.54209169 0.37749638
  0.34393691 0.48260098 0.47772576 0.47210611]
 [0.59658476 0.92890368 0.75583816 0.8128711  1.0960596  0.91615216
  0.91896086 0.91135471 0.76811755 1.15102863]
 [0.75567409 1.47326254 0.98075817 1.23661445 1.29197235 1.25242598
  1.42686452 1.42102623 1.14570729 1.55201736]
 [0.3856832  0.90328374 0.48536669 0.72097506 0.59561534 0.67174027
  0.85126857 0.87008155 0.68757511 0.8206931 ]
 [0.55700639 1.01014095 0.5647267  0.770066   0.8948852  0.81882993
  0.92233816